package generic.interfaces;

/**
 * Creator: Yao
 * Date:    2016/7/20
 * For:
 * Other:
 */
public enum Colors {
    ZINC, LEMON_YELLOW, MEDIUM_YELLOW, DEEP_YELLOW, ORANGE, BRILLIANT_RED,
    CRIMSON, MAGENTA, ROSE_MADDER, VIOLET, PHTHALO_BLUE, ULTRAMARINE,
    PERMANENT_GREEN, VIRIDIAN_HUE, SAP_GREEN, YELLOW_OCHRE, BURNT_SIENNA, RAW_UMBER
}
